import { Content } from './content';

export class Creature extends Content {
    name: string = '';
    description: string | null = null;
    level: number = 1;
    life: number | null = 30;
    pa: number | null = 6;
    pm: number | null = 3;
    po: number | null = 0;
    ini: number | null = 0;
    touch: number | null = 0;
    ca: number | null = 0;
    dodge_pa: number | null = 0;
    dodge_pm: number | null = 0;
    fuite: number | null = 0;
    tacle: number | null = 0;
    vitality: number | null = 0;
    sagesse: number | null = 0;
    strong: number | null = 0;
    intel: number | null = 0;
    agi: number | null = 0;
    chance: number | null = 0;
    do_fixe_neutre: string | null = '0';
    do_fixe_terre: string | null = '0';
    do_fixe_feu: string | null = '0';
    do_fixe_air: string | null = '0';
    do_fixe_eau: string | null = '0';
    do_fixe_multiple: string | null = '0';
    res_neutre: number | null = 0;
    res_terre: number | null = 0;
    res_feu: number | null = 0;
    res_air: number | null = 0;
    res_eau: number | null = 0;
    acrobatie_bonus: number | null = 0;
    discretion_bonus: number | null = 0;
    escamotage_bonus: number | null = 0;
    athletisme_bonus: number | null = 0;
    intimidation_bonus: number | null = 0;
    arcane_bonus: number | null = 0;
    histoire_bonus: number | null = 0;
    investigation_bonus: number | null = 0;
    nature_bonus: number | null = 0;
    religion_bonus: number | null = 0;
    dressage_bonus: number | null = 0;
    medecine_bonus: number | null = 0;
    perception_bonus: number | null = 0;
    perspicacite_bonus: number | null = 0;
    survie_bonus: number | null = 0;
    persuasion_bonus: number | null = 0;
    representation_bonus: number | null = 0;
    supercherie_bonus: number | null = 0;
    acrobatie_mastery: number | null = 0;
    discretion_mastery: number | null = 0;
    escamotage_mastery: number | null = 0;
    athletisme_mastery: number | null = 0;
    intimidation_mastery: number | null = 0;
    arcane_mastery: number | null = 0;
    histoire_mastery: number | null = 0;
    investigation_mastery: number | null = 0;
    nature_mastery: number | null = 0;
    religion_mastery: number | null = 0;
    dressage_mastery: number | null = 0;
    medecine_mastery: number | null = 0;
    perception_mastery: number | null = 0;
    perspicacite_mastery: number | null = 0;
    survie_mastery: number | null = 0;
    persuasion_mastery: number | null = 0;
    representation_mastery: number | null = 0;
    supercherie_mastery: number | null = 0;
    kamas: string | null = null;
    drop_: string | null = null;
    other_item: string | null = null;
    other_consumable: string | null = null;
    other_spell: string | null = null;

    constructor(data: Partial<Creature>) {
        super(data);
        this.hydrate(data);
    }
}